package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Note;
import greendao.Customer;
import greendao.Order;
import greendao.Users;
import greendao.infoType;
import greendao.infos;

import greendao.NoteDao;
import greendao.CustomerDao;
import greendao.OrderDao;
import greendao.UsersDao;
import greendao.infoTypeDao;
import greendao.infosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig usersDaoConfig;
    private final DaoConfig infoTypeDaoConfig;
    private final DaoConfig infosDaoConfig;

    private final NoteDao noteDao;
    private final CustomerDao customerDao;
    private final OrderDao orderDao;
    private final UsersDao usersDao;
    private final infoTypeDao infoTypeDao;
    private final infosDao infosDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        infoTypeDaoConfig = daoConfigMap.get(infoTypeDao.class).clone();
        infoTypeDaoConfig.initIdentityScope(type);

        infosDaoConfig = daoConfigMap.get(infosDao.class).clone();
        infosDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);
        infoTypeDao = new infoTypeDao(infoTypeDaoConfig, this);
        infosDao = new infosDao(infosDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Customer.class, customerDao);
        registerDao(Order.class, orderDao);
        registerDao(Users.class, usersDao);
        registerDao(infoType.class, infoTypeDao);
        registerDao(infos.class, infosDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        usersDaoConfig.getIdentityScope().clear();
        infoTypeDaoConfig.getIdentityScope().clear();
        infosDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public infoTypeDao getInfoTypeDao() {
        return infoTypeDao;
    }

    public infosDao getInfosDao() {
        return infosDao;
    }

}
